genj_faq_search_show:
    path: /faq/search/{slug}
    defaults:
        _controller: GenjFaqBundle:Search:show
        slug: null

genj_faq_faq_index:
    path: /faq/{categorySlug}/{questionSlug}
    defaults:
        _controller: GenjFaqBundle:Faq:index
        categorySlug: null
        questionSlug: null

genj_faq_question_show:
    path: /faq/{categorySlug}/{slug}
    defaults:
        _controller: GenjFaqBundle:Question:show